import { Tenant } from '@/dataAccess/models/Tenant';
import { PaymentType } from '@/enums/PaymentType';
import { TenantClientType } from '@/enums/TenantClientType';
import { TenantState } from '@/enums/TenantState';
import { WAVerificationStatus } from '@/enums/WAVerificationStatus';
import { DateTime } from 'luxon';

export const ACTIVE_TENANT: Tenant = {
  DbName: null,
  ConnectionString: null,
  TenantId: null,
  BackendDomain: 'live-server-111111.watiapp.io',
  StripeCustomerId: 'stribeCustomIdActive',
  FrontEndUrl: 'live-111111.watiapp.io',
  StripeSubscriptionId: 'subscriptionIdActive',
  WATIProduct: 'WATI',
  WADisplayName: 'displayNameActive',
  WABAID: '111111111111111',
  WAGatewayUrl: null,
  WAGatewayAdminPassword: null,
  WAConnectionType: 'REST',
  WAVerificationStatus: WAVerificationStatus.APPROVED,
  WAVerified: 'VERIFIED',
  WAVerifiedDate: null,
  State: TenantState.AUTOMATED_REGISTERED,
  Note: null,
  ClientType: TenantClientType.REGULAR_CLIENT,
  WACertificate: null,
  WABAPhoneInfo: {
    display_phone_number: '10000000000',
    certificate: '',
  },
  ClientFirstName: 'uyen',
  ClientLastName: 'ntt',
  ClientEmail: 'testActive@clare.ai',
  ClientPhone: '80000000000',
  ClientCompanyName: 'clare',
  RetryCount: null,
  PaymentType: PaymentType.CHARGEBEE,
  CustomSubDomain: false,
  GreenTickApplication: false,
  ProPlan: false,
  MaxNumberOperators: 5,
  BMID: '911111111111111',
  HubSpotAdded: false,
  RetryAfter: null,
  Created: new Date(),
  LastUpdated: new Date(),
  WATIAdminPassword: 'password',
  WABAStatusLastUpdated: null,
};
export const INACTIVE_TENANT: Tenant = {
  DbName: null,
  ConnectionString: null,
  TenantId: null,
  BackendDomain: 'live-server-111112.watiapp.io',
  StripeCustomerId: 'AzZj7CTSSbjijgS9',
  FrontEndUrl: 'live-111112.watiapp.io',
  WATIAdminPassword: 'password',
  StripeSubscriptionId: 'stripeSubscriptionidInactive',
  WATIProduct: 'WATI',
  WADisplayName: 'displayNameInactive',
  WABAID: '111111111111112',
  WAGatewayUrl: null,
  WAGatewayAdminPassword: null,
  WAConnectionType: 'REST',
  WAVerificationStatus: WAVerificationStatus.APPROVED,
  WAVerified: 'VERIFIED',
  WAVerifiedDate: null,
  State: TenantState.SUSPEND,
  Note: null,
  ClientType: TenantClientType.REGULAR_CLIENT,
  WACertificate: null,
  WABAPhoneInfo: {
    display_phone_number: '10000000001',
    certificate: '',
  },
  ClientFirstName: 'uyen',
  ClientLastName: 'ntt',
  ClientEmail: 'testInactive@clare.ai',
  ClientPhone: '80000000001',
  ClientCompanyName: 'clare',
  RetryCount: null,
  PaymentType: PaymentType.CHARGEBEE,
  CustomSubDomain: false,
  GreenTickApplication: false,
  ProPlan: false,
  MaxNumberOperators: 5,
  BMID: '911111111111112',
  HubSpotAdded: false,
  RetryAfter: null,
  Created: new Date(),
  LastUpdated: new Date(),
  WABAStatusLastUpdated: null,
};
export const YESTERDAY_CREATED_ACTIVE_TENANT: Tenant = {
  DbName: null,
  ConnectionString: null,
  TenantId: null,
  BackendDomain: 'live-server-111113.watiapp.io',
  StripeCustomerId: 'stribeCustomIdYesterdayActive',
  FrontEndUrl: 'live-111113.watiapp.io',
  StripeSubscriptionId: 'subscriptionIdYesterdayActive',
  WATIProduct: 'WATI',
  WADisplayName: 'displayNameYesterdayActive',
  WABAID: '111111111111113',
  WAGatewayUrl: null,
  WAGatewayAdminPassword: null,
  WAConnectionType: 'REST',
  WAVerificationStatus: WAVerificationStatus.APPROVED,
  WAVerified: 'VERIFIED',
  WAVerifiedDate: null,
  State: TenantState.AUTOMATED_REGISTERED,
  Note: null,
  ClientType: TenantClientType.REGULAR_CLIENT,
  WACertificate: null,
  WABAPhoneInfo: {
    display_phone_number: '10000000002',
    certificate: '',
  },
  ClientFirstName: 'uyen',
  ClientLastName: 'ntt',
  ClientEmail: 'testYesterdayActive@clare.ai',
  ClientPhone: '80000000002',
  ClientCompanyName: 'clare',
  RetryCount: null,
  PaymentType: PaymentType.CHARGEBEE,
  CustomSubDomain: false,
  GreenTickApplication: false,
  ProPlan: false,
  MaxNumberOperators: 5,
  BMID: '911111111111113',
  HubSpotAdded: false,
  RetryAfter: null,
  Created: DateTime.now().minus({ day: 1 }).toJSDate(),
  LastUpdated: DateTime.now().minus({ day: 1 }).toJSDate(),
  WATIAdminPassword: 'password',
  WABAStatusLastUpdated: null,
};
