/* eslint-disable */
// @ts-nocheck
import { isNodeEnv, NodeEnv } from '@/enums/NodeEnv';

interface Environment {
  JWT_SECRET: string;
  // adminUser_DB_URL: string;
  database_DB_URL: string;
  // tenants_DB_URL: string;
  TENANTS_DATABASE: string;
  NEXT_PUBLIC_DB_AUTH_DATABASE: string;
  NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION: string;
  NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION: string;
  NEXT_PUBLIC_DB_AUTH_TABLE_ACCESS_SETTING_COLLECTION: string;
  NEXT_PUBLIC_DB_AUTH_COLUMN_ACCESS_SETTING_COLLECTION: string;
  NODE_ENV: NodeEnv;
  LOG_LEVEL: string | undefined;
  GCP_PROJECT_ID: string;
  NEXT_PUBLIC_DB_TENANT_CONTACT_COLLECTION: string;
  NEXT_PUBLIC_DB_AUTH_CONTACT_ACTIVITY_LOG_COLLECTION: string;
  NEXT_PUBLIC_DB_AUTH_CREATE_USER_LOG_COLLECTION: string;
  NEXT_PUBLIC_DB_AUTH_TERMINATE_SUBSCRIPTION_LOG_COLLECTION: string;
  MT_USER_COLLECTION_NAME: string;
  FB_VERSION: string;
  FB_SYSTEM_TOKEN: string;
  CLARE_SECRET_KEY: string;
  AUDIT_LOG_DATABASE: string;
  PRM_GATEWAY_DB_USER: string;
  PRM_GATEWAY_DB_PASSWORD: string;
  PRM_GATEWAY_DB_HOST: string;
  PRM_GATEWAY_DB_PORT: string;
  PRM_GATEWAY_DB_NAME: string;
  RETOOL_API_KEY: string;
  BILLING_DB_URL: string;
  BILLING_DATABASE: string;
}
interface PublicEnvironment {
  NEXT_PUBLIC_DB_AUTH_DATABASE: string;
  NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION: string;
  NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION: string;
  NEXT_PUBLIC_FB_WABA_ID: string;
}

export const getEnv = (): Environment => {
  if (
    !process.env.JWT_SECRET ||
    !process.env.DB_URL ||
    !process.env.TENANTS_DATABASE ||
    !process.env.NEXT_PUBLIC_DB_AUTH_DATABASE ||
    !process.env.NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION ||
    !process.env.NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION ||
    !isNodeEnv(process.env.NODE_ENV) ||
    !process.env.GCP_PROJECT_ID ||
    !process.env.NEXT_PUBLIC_DB_AUTH_COLUMN_ACCESS_SETTING_COLLECTION ||
    !process.env.NEXT_PUBLIC_DB_AUTH_TABLE_ACCESS_SETTING_COLLECTION ||
    !process.env.NEXT_PUBLIC_DB_TENANT_CONTACT_COLLECTION ||
    !process.env.NEXT_PUBLIC_DB_AUTH_CONTACT_ACTIVITY_LOG_COLLECTION ||
    !process.env.NEXT_PUBLIC_DB_AUTH_CREATE_USER_LOG_COLLECTION ||
    !process.env.NEXT_PUBLIC_DB_AUTH_TERMINATE_SUBSCRIPTION_LOG_COLLECTION ||
    !process.env.FB_VERSION ||
    !process.env.FB_SYSTEM_TOKEN ||
    !process.env.CLARE_SECRET_KEY
  ) {
    console.error('getEnv:invalid_config');

    throw new Error('invalid_config');
  }

  console.debug(
    'process.env.NEXT_PUBLIC_DB_AUTH_DATABASE',
    process.env.NEXT_PUBLIC_DB_AUTH_DATABASE,
  );

  return {
    JWT_SECRET: process.env.JWT_SECRET,
    database_DB_URL: process.env.DB_URL,
    TENANTS_DATABASE: process.env.TENANTS_DATABASE,
    NEXT_PUBLIC_DB_AUTH_DATABASE: process.env.NEXT_PUBLIC_DB_AUTH_DATABASE,
    NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION:
      process.env.NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION,
    NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION:
      process.env.NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION,
    NODE_ENV: process.env.NODE_ENV,
    LOG_LEVEL: process.env.LOG_LEVEL,
    GCP_PROJECT_ID: process.env.GCP_PROJECT_ID,
    NEXT_PUBLIC_DB_AUTH_COLUMN_ACCESS_SETTING_COLLECTION:
      process.env.NEXT_PUBLIC_DB_AUTH_COLUMN_ACCESS_SETTING_COLLECTION,
    NEXT_PUBLIC_DB_AUTH_TABLE_ACCESS_SETTING_COLLECTION:
      process.env.NEXT_PUBLIC_DB_AUTH_TABLE_ACCESS_SETTING_COLLECTION,
    NEXT_PUBLIC_DB_TENANT_CONTACT_COLLECTION:
      process.env.NEXT_PUBLIC_DB_TENANT_CONTACT_COLLECTION,
    NEXT_PUBLIC_DB_AUTH_CONTACT_ACTIVITY_LOG_COLLECTION:
      process.env.NEXT_PUBLIC_DB_AUTH_CONTACT_ACTIVITY_LOG_COLLECTION,
    NEXT_PUBLIC_DB_AUTH_CREATE_USER_LOG_COLLECTION:
      process.env.NEXT_PUBLIC_DB_AUTH_CREATE_USER_LOG_COLLECTION,
    MT_USER_COLLECTION_NAME: process.env.MT_USER_COLLECTION_NAME,
    NEXT_PUBLIC_DB_AUTH_TERMINATE_SUBSCRIPTION_LOG_COLLECTION:
      process.env.NEXT_PUBLIC_DB_AUTH_TERMINATE_SUBSCRIPTION_LOG_COLLECTION,
    BILLING_DB_URL: process.env.BILLING_DB_URL,
    BILLING_DATABASE: process.env.BILLING_DATABASE,
    FB_VERSION: process.env.FB_VERSION,
    FB_SYSTEM_TOKEN: process.env.FB_SYSTEM_TOKEN,
    CLARE_SECRET_KEY: process.env.CLARE_SECRET_KEY,
    AUDIT_LOG_DATABASE: process.env.AUDIT_LOG_DATABASE,
    PRM_GATEWAY_DB_USER: process.env.PRM_GATEWAY_DB_USER,
    PRM_GATEWAY_DB_PASSWORD: process.env.PRM_GATEWAY_DB_PASSWORD,
    PRM_GATEWAY_DB_HOST: process.env.PRM_GATEWAY_DB_HOST,
    PRM_GATEWAY_DB_PORT: process.env.PRM_GATEWAY_DB_PORT,
    PRM_GATEWAY_DB_NAME: process.env.PRM_GATEWAY_DB_NAME,
    PRICING_DATABASE: process.env.PRICING_DATABASE,
    PRICING_DB_URL: process.env.PRICING_DB_URL,
    RETOOL_API_KEY: process.env.RETOOL_API_KEY,
  };
};

export const getPublicEnv = (): PublicEnvironment => {
  if (
    !process.env.NEXT_PUBLIC_DB_AUTH_DATABASE ||
    !process.env.NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION ||
    !process.env.NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION ||
    !process.env.NEXT_PUBLIC_FB_WABA_ID
  ) {
    console.error('getPublicEnv:invalid_config');

    throw new Error('invalid_config');
  }

  console.debug(
    'getPublicEnv process.env.NEXT_PUBLIC_DB_AUTH_DATABASE',
    process.env.NEXT_PUBLIC_DB_AUTH_DATABASE,
  );

  return {
    NEXT_PUBLIC_DB_AUTH_DATABASE: process.env.NEXT_PUBLIC_DB_AUTH_DATABASE,
    NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION:
      process.env.NEXT_PUBLIC_DB_AUTH_ADMIN_USER_COLLECTION,
    NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION:
      process.env.NEXT_PUBLIC_DB_TENANT_TENANT_COLLECTION,
    NEXT_PUBLIC_FB_WABA_ID: process.env.NEXT_PUBLIC_FB_WABA_ID,
  };
};
