export enum TenantState {
  AUTOMATED_PENDING = 'AUTOMATED_PENDING',
  AUTOMATED_PROVISIONED1 = 'AUTOMATED_PROVISIONED1',
  AUTOMATED_PROVISIONED2 = 'AUTOMATED_PROVISIONED2',
  AUTOMATED_READY = 'AUTOMATED_READY',
  AUTOMATED_READY1 = 'AUTOMATED_READY1',
  AUTOMATED_REGISTERED = 'AUTOMATED_REGISTERED',
  ACTIVE = 'Active',
  C_AUTOMATED_READY = 'C_AUTOMATED_READY',
  C_PROVISION_READY = 'C_PROVISION_READY',
  EMBEDDED_SIGNUP_FAILED = 'EMBEDDED_SIGNUP_FAILED',
  SUSPEND = 'Suspend',
  C_PROVISION_READY_FOR_INSTANCE = 'C_PROVISION_READY_FOR_INSTANCE',
}

export const allTenantStates = [
  TenantState.AUTOMATED_PENDING,
  TenantState.AUTOMATED_PROVISIONED1,
  TenantState.AUTOMATED_PROVISIONED2,
  TenantState.AUTOMATED_READY,
  TenantState.AUTOMATED_READY1,
  TenantState.AUTOMATED_REGISTERED,
  TenantState.ACTIVE,
  TenantState.C_AUTOMATED_READY,
  TenantState.C_PROVISION_READY,
  TenantState.EMBEDDED_SIGNUP_FAILED,
  TenantState.SUSPEND,
  TenantState.C_PROVISION_READY_FOR_INSTANCE,
];
